#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Allow push in github actions without prompting for confirmation
if [ -n "$CI" ]; then exit 0; fi

protected_branch='main'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
  echo "${protected_branch} is a protected branch"
  read -p "Push ${protected_branch} (y/N)? " choice < /dev/tty
  case "$choice" in
    y|Y ) exit 0;;
  esac

  echo "Push cancelled"
  exit 1 # push will not execute
fi

exit 0 # push will execute
